version: "3.8"

services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  frontend:
    build: ./client
    ports:
      - "5173:80"
    depends_on:
      - backend
